
# import os
# import tempfile
# from typing import IO
# from io import BytesIO
# from dotenv import load_dotenv
# from elevenlabs import VoiceSettings, save
# from elevenlabs.client import ElevenLabs

# from io import BytesIO
# # from pydub import AudioSegment
# # from pydub.playback import play 
# from playsound3 import playsound # <<< Use playsound3

# # import simpleaudio as sa
# load_dotenv()

# ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY")
# elevenlabs = ElevenLabs(
#     api_key=ELEVENLABS_API_KEY,
# )


# # Define the text you want to convert
# text_to_speak = "Hello! This is an example of text to speech generated by ElevenLabs."

# response = elevenlabs.text_to_speech.convert(
#         voice_id="pNInz6obpgDQGcFmaJgB", # Adam pre-made voice
#         output_format="mp3_22050_32",
#         text=text_to_speak,
#         model_id="eleven_turbo_v2_5", # use the turbo model for low latency
#         # Optional voice settings that allow you to customize the output
#         voice_settings=VoiceSettings(
#             stability=0.0,
#             similarity_boost=1.0,
#             style=0.0,
#             use_speaker_boost=True,
#             speed=1.0,
#         ),
#     )
# # uncomment the line below to play the audio back
# # play(response)
# # Generating a unique file name for the output MP3 file
# save_file_path = "output.mp3"
# # Writing the audio to a file
# with open(save_file_path, "wb") as f:
#     for chunk in response:
#         if chunk:
#             f.write(chunk)   


# try:
#     # 3. Play the Audio using playsound3
#     print("Starting playback with playsound3...")
#     # playsound3 can handle MP3 files on Windows natively via winmm.dll
#     playsound(save_file_path) 
#     print("Playback finished.")

# finally:
#     # 4. Clean up the temporary file
#     os.remove(save_file_path)
#     print("Temporary file cleaned up.")


from pyhtml2pdf import converter
# Convert from URL
converter.convert('templates\index.html', 'sample.pdf')
# Convert from local HTML file
import os
path = os.path.abspath('index.html')
converter.convert(f'file:///{path}', 'sample.pdf')